### ISSUE TITLE
Plugin Broken with Resources 1.2.9

### ISSUE THREAD

**Issue by ianpgall** [mckenfra/gsp-resources#12]
I recently upgraded the Resources plugin to version 1.2.13 (from 1.2.7), to have the most recent version. With that upgrade, the application suddenly couldn't find GSP resources anymore. I backtracked the version of the Resources plugin to 1.2.8, to find that it's the last version that works (with the GSP Resources plugin, version 0.4.4). If it helps, here's the stacktrace:

```
org.codehaus.groovy.grails.web.mapping.exceptions.UrlMappingException: Error mapping onto view [/index]: Error applying layout : main
    at org.tuckey.web.filters.urlrewrite.RuleChain.handleRewrite(RuleChain.java:176)
    at org.tuckey.web.filters.urlrewrite.RuleChain.doRules(RuleChain.java:145)
    at org.tuckey.web.filters.urlrewrite.UrlRewriter.processRequest(UrlRewriter.java:92)
    at org.tuckey.web.filters.urlrewrite.UrlRewriteFilter.doFilter(UrlRewriteFilter.java:389)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:745)
Caused by: org.codehaus.groovy.grails.web.pages.exceptions.GroovyPagesException: Error applying layout : main
    ... 7 more
Caused by: org.codehaus.groovy.grails.web.pages.exceptions.GroovyPagesException: Error processing GroovyPageView: Error executing tag <r:layoutResources>: Module [applicationFiles] depends on resource [/js/util/urls.js.gsp] but the file cannot be found
    ... 7 more
Caused by: org.codehaus.groovy.grails.web.taglib.exceptions.GrailsTagException: Error executing tag <r:layoutResources>: Module [applicationFiles] depends on resource [/js/util/urls.js.gsp] but the file cannot be found
    at home_igall_git_ggsafechx_grails_app_views_layouts_main_gsp$_run_closure1.doCall(home_igall_git_ggsafechx_grails_app_views_layouts_main_gsp:55)
    at home_igall_git_ggsafechx_grails_app_views_layouts_main_gsp.run(home_igall_git_ggsafechx_grails_app_views_layouts_main_gsp:60)
    ... 7 more
Caused by: java.lang.IllegalArgumentException: Module [applicationFiles] depends on resource [/js/util/urls.js.gsp] but the file cannot be found
    at org.grails.plugin.resource.ResourceTagLib$_closure10.doCall(ResourceTagLib.groovy:456)
    at org.grails.plugin.resource.ResourceTagLib$_closure6.doCall(ResourceTagLib.groovy:377)
    ... 9 more
```

Like I said, just changing the Resources plugin down to version 1.2.8, and without any other changes, everything works fine.

Is there anything that can be done? Or is this a local problem with my app?

**Comment by mckenfra** [comment]
Thanks for raising this. I'll need to take a look at what's changed with the resources plugin in v1.2.9. I'll get back to you once I've looked into it.

Cheers,
Francis

**Comment by ianpgall** [comment]
@mckenfra Sounds good, thanks! I did try looking at the Resources plugin's source code and commits between 1.2.8 and 1.2.9, but I'm really not sure what to look for :(
